# Generated by Django 5.2.1 on 2025-08-12 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0029_pagemedia'),
        ('page', '0031_alter_page_metadata_alter_page_private_metadata_and_more'),
    ]

    operations = [
    ]
